---
- name: Clone Configuration Repositories
  hosts: all
  become: true
  tasks:
    - name: Clone Homepage Configuration Files
      ansible.builtin.git:
        repo: https://github.com/Xavier2p/homepage.git
        dest: /docker/homepage
        version: main
        clone: true
        update: true
        force: true
