---
- name: Initial Config for Hosts
  hosts: all
  become: true

  tasks:
    - name: Create Root Docker Folder
      ansible.builtin.file:
        path: /docker
        state: directory
        mode: '0755'
        recurse: true
        owner: sysadmin
        group: sysadmin

    - name: Create Infra Folder
      ansible.builtin.file:
        path: /infra
        state: directory
        mode: '0755'
        recurse: true
        owner: sysadmin
        group: sysadmin

    - name: Create tree in it
      ansible.builtin.file:
        path: /docker/{{ item }}
        state: directory
        mode: '0755'
      loop:
        - uptime-kuma
        - traefik
        - portainer
        - homepage
        - adguard
        - homer
        - dozzle
        - code-server
        - grafana
        - prometheus

    - name: Assign good right to Traefik
      ansible.builtin.file:
        path: /docker/traefik/acme.json
        owner: sysadmin
        group: sysadmin
        mode: '0600'

    - name: Create Downloads Folder
      ansible.builtin.file:
        path: /downloads
        state: directory
        mode: '0755'
        recurse: true
        owner: sysadmin
        group: sysadmin

    - name: Create tree in it
      ansible.builtin.file:
        path: /downloads/{{ item }}
        state: directory
        mode: '0755'
      loop:
        - movies
        - series
        - music
        - ytdl
        - photos
        - other
