---
- name: Create Folders for Configuration
  hosts: all
  become: true
  tasks:
    - name: Create Root Docker Folder
      ansible.builtin.file:
        path: /docker
        state: directory
        mode: '0757'
        recurse: true
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Create tree in it
      ansible.builtin.file:
        path: /docker/{{ item }}
        state: directory
        mode: '0757'
      loop:
        - uptime-kuma
        - traefik
        # - portainer
        - homepage
        - adguard
        - homer
        # - code-server
        - grafana
        - prometheus
        # - jellyfin
        # - jellyseerr
        # - sonarr
        # - radarr
        # - jackett

    - name: Assign good right to Traefik
      ansible.builtin.file:
        path: /docker/traefik/acme.json
        state: touch
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0600'

    - name: Create Downloads Folder
      ansible.builtin.file:
        path: /downloads
        state: directory
        mode: '0757'
        recurse: true
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Create tree in it
      ansible.builtin.file:
        path: /downloads/{{ item }}
        state: directory
        mode: '0757'
      loop:
        - movies
        - series
        - music
        - ytdl
        - photos
        - other
