---
- name: Install Raspberry Pi
  hosts: all
  become: true

  tasks:
      # Updates the repository cache
      - name: Update
        ansible.builtin.apt:
            update_cache: true

      # Upgrades all packages
      - name: Upgrade
        ansible.builtin.apt:
            upgrade: dist

      # Installs the required packages for Docker
      - name: Install APT packages
        ansible.builtin.apt:
            name:
                - apt-transport-https
                - ca-certificates
                - lsb-release
                - gnupg
                - zsh
                - vim
            state: latest
            update_cache: true

      # Gets the Docker signing key
      - name: Add signing key - Docker
        ansible.builtin.apt_key:
            url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
            state: present

      # Adds the Docker repository to the sources list
      - name: Add repository into sources list - Docker
        ansible.builtin.apt_repository:
            repo: 'deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
            state: present
            filename: docker

      # Installs Docker
      - name: Install Docker
        ansible.builtin.apt:
            name:
                - docker
                - docker.io
                - docker-compose
                - docker-registry
            state: latest
            update_cache: true

      # Downloads the binary for Terraform
      - name: Download Terraform
        ansible.builtin.get_url:
            url: 'https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_arm64.zip'
            dest: /tmp/terraform.zip
            mode: '0755'

      # Unzips the Terraform binary to the bin directory
      - name: Unzip Terraform
        ansible.builtin.unarchive:
            src: /tmp/terraform.zip
            dest: /usr/local/bin
            remote_src: true
            mode: '0755'
