---
- name: Prepare environment
  ansible.builtin.import_playbook: preprocess.yml

- name: Install Docker Playbook
  ansible.builtin.import_playbook: install-docker.yml

- name: Init Hosts Playbook
  ansible.builtin.import_playbook: init-hosts.yml

- name: Retrieve Configuration Files
  ansible.builtin.import_playbook: clone-repo.yml
