---
- name: Install Raspberry Pi
  hosts: all
  become: yes

  tasks:
      # Updates the repository cache
      - name: Update
        apt: update_cache=yes

      # Upgrades all packages
      - name: Upgrade
        apt: upgrade=dist

      # Installs the required packages for Docker
      - name: Install apt-transport-https
        ansible.builtin.apt:
            name:
                - apt-transport-https
                - ca-certificates
                - lsb-release
                - gnupg
            state: latest
            update_cache: true

      # Gets the Docker signing key
      - name: Add signing key - Docker
        ansible.builtin.apt_key:
            url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
            state: present

      # Adds the Docker repository to the sources list
      - name: Add repository into sources list - Docker
        ansible.builtin.apt_repository:
            repo: 'deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
            state: present
            filename: docker

      # Installs Docker
      - name: Install Docker
        ansible.builtin.apt:
            name:
                - docker
                - docker.io
                - docker-compose
                - docker-registry
            state: latest
            update_cache: true

      # Downloads the binary for Terraform
      - name: Download Terraform
        ansible.builtin.get_url:
            url: 'https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_arm64.zip'
            dest: /tmp/terraform.zip
            mode: 0755

      # Unzips the Terraform binary to the bin directory
      - name: Unzip Terraform
        ansible.builtin.unarchive:
            src: /tmp/terraform.zip
            dest: /usr/local/bin
            remote_src: yes
            mode: 0755
