---
name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Format Code
        run: terraform fmt -check -recursive

      - name: Get Modules
        run: terraform get

      - name: Init Terraform
        run: terraform init

      - name: Validate Configuration
        run: terraform validate
