---
name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hosts/scariff
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Format
        run: terraform fmt -check -recursive

      - name: Get
        run: terraform get

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate
